const { defineConfig } = require("cypress");

module.exports = defineConfig({
projectId: '3ykw63',
  // e2e: {
  //   setupNodeEvents(on, config) {
      
  //   },
  // }

  animationDistanceThreshold: 5,
  arch: 'x64',
  baseUrl: null,
  blockHosts: null,
  browsers: [
  {
  name: 'chrome',
  family: 'chromium',
  channel: 'stable',
  displayName: 'Chrome',
  version: '107.0.5304.107',
  path: 'C:\Program Files\Google\Chrome\Application\chrome.exe',
  minSupportedVersion: 64,
  majorVersion: '107',
  },
  {
  name: 'firefox',
  family: 'firefox',
  channel: 'stable',
  displayName: 'Firefox',
  version: '107.0',
  path: 'C:\Program Files\Mozilla Firefox\firefox.exe',
  minSupportedVersion: 86,
  majorVersion: '107',
  },
  {
  name: 'edge',
  family: 'chromium',
  channel: 'stable',
  displayName: 'Edge',
  version: '107.0.1418.52',
  path: 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe',
  minSupportedVersion: 79,
  majorVersion: '107',
  },
  {
  name: 'electron',
  channel: 'stable',
  family: 'chromium',
  displayName: 'Electron',
  version: '102.0.5005.148',
  path: '',
  majorVersion: 102,
  info: 'Electron is the default browser that comes with Cypress. This is the default browser that runs in headless mode. Selecting this browser is useful when debugging. The version number indicates the underlying Chromium version that Electron uses.',
  },
  ],
  chromeWebSecurity: true,
  clientCertificates: [],
  defaultCommandTimeout: 6000,
  downloadsFolder: 'cypress/downloads',
  env: {
  },
  excludeSpecPattern: '*.hot-update.js',
  execTimeout: 60000,
  experimentalFetchPolyfill: false,
  experimentalInteractiveRunEvents: false,
  experimentalModifyObstructiveThirdPartyCode: false,
  experimentalSessionAndOrigin: false,
  experimentalSourceRewriting: false,
  fileServerFolder: '',
  fixturesFolder: 'cypress/fixtures',
  hosts: null,
  includeShadowDom: false,
  isInteractive: true,
  keystrokeDelay: 0,
  modifyObstructiveCode: true,
  nodeVersion: null,
  numTestsKeptInMemory: 50,
  pageLoadTimeout: 60000,
  platform: 'win32',
  port: null,
  projectId: '3ykw63',
  redirectionLimit: 20,
  reporter: 'spec',
  reporterOptions: null,
  requestTimeout: 5000,
  resolvedNodePath: null,
  resolvedNodeVersion: null,
  responseTimeout: 30000,
  retries: {
  runMode: 1,
  openMode: 1,
  },
  screenshotOnRunFailure: true,
  screenshotsFolder: 'cypress/screenshots',
  scrollBehavior: 'top',
  slowTestThreshold: 10000,
  specPattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}',
  supportFile: 'cypress/support/e2e.{js,jsx,ts,tsx}',
  supportFolder: false,
  taskTimeout: 60000,
  testIsolation: 'legacy',
  trashAssetsBeforeRuns: true,
  userAgent: null,
  video: true,
  videoCompression: 32,
  videosFolder: 'cypress/videos',
  videoUploadOnPasses: true,
  viewportHeight: 660,
  viewportWidth: 1000,
  waitForAnimations: true,
  watchForFileChanges: true,
  }
);